### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by syunakh** [paypal/Checkout-NET-SDK#11]
There is problem with serialization for patching of order

> Type 'PayPalCheckoutSdk.Orders.PurchaseUnit' with data contract name 'Money:http://schemas.datacontract.org/2004/07/PayPalCheckoutSdk.Orders' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

```
var patches = new List<Patch<object>>
             {
                new Patch<object>
                {
                    Op = "replace",
                    Path = $"/purchase_units/@reference_id=='{_referenceId}'",
                    Value = new PurchaseUnit
                    {
                        ReferenceId = _referenceId,
                        Amount = new AmountWithBreakdown
                        {
                            Value = "100",
                            CurrencyCode = "USD",                            
                        },

                       ....
                    }
                },
             };

            request.RequestBody(patches);
```

it works correctly if added attribute [KnownType(typeof...)] for each entity which is used for patching (PurchaseUnit, AmountWithBreakdown, Money, etc.)

**Comment by rajarampadmanathan** [comment]
Will look into it and get back to you

**Comment by dan-hartley** [comment]
Any more information on this or any workaround?  I'm attempting to patch the amount of an order, but am running into the same data contract exception described here.  

I can replace simple attributes like "purchase_units[].description" fine, but replacing any object like "purchase_units[].amount" throws this exception.

**Comment by danjrichardson** [comment]
I had the same issue when trying to update an amount using `AmountWithBreakdown`.
I've managed to get around the problem by typing the generic `Patch<T>` object with `AmountWithBreakdown` instead. I'm fairly sure that you could type if with `PurchaseUnit` and achieve a positive result
