### ISSUE TITLE
Error while trying to use different currency than USD

### ISSUE THREAD

**Issue by BibekStha** [paypal/Checkout-NET-SDK#16]
I get this error while trying to use any currency code other than USD:

Uncaught Error: Expected currency from order api call to be USD, got CAD. Please ensure you are passing currency=CAD to the sdk

It says, it is expecting the currency to be USD. Why is that? and how to change or disable that?

**Comment by rajarampadmanathan** [comment]
HI @BibekStha - Can you please provide more details to replicate the issue? Like what is the request you're trying to send, stack trace of the error, paypal debug id, etc..

**Comment by rajarampadmanathan** [comment]
Just to confirm ... you’re using .NET sdk or PayPal js sdk ?

**Comment by BibekStha** [comment]
I use PayPal JS SDK to render the buttons. I'm using this [Checkout-NET-SDK](https://github.com/paypal/Checkout-NET-SDK) to call the API from backend server.

I use the currencycode in the BuildRequestBody method like this:
`PurchaseUnits = new List<PurchaseUnitRequest>
                {
                    new PurchaseUnitRequest
                    {
                        ReferenceId = "HospDonat",
                        Description = "Donation",
                        Amount = new AmountWithBreakdown
                        {
                            CurrencyCode = "USD",
                            Value = 10
                        }
                    }
                }`

Hope that helps.

**Comment by rajarampadmanathan** [comment]
@BibekStha - I believe you're getting this error from PayPal JS SDK and not .NET SDK.  Do you any logs to trace that the cal actually made from JS SDK .NET SDK? If yes, what is the request you received on .NET SDK?

@bluepnume - Is it something related to PayPal JS SDK? Do we have any currency related check ?

**Comment by BibekStha** [comment]
@rajarampadmanathan - You were right. It was the issue with JS SDK. I found the solution after some more googling [here](https://github.com/paypal/Checkout-PHP-SDK/issues/11). We need to add 'currency=CAD' to the JS url like: 
`<script src="https://www.paypal.com/sdk/js?client-id=<client_id>&currency=CAD while getting"></script>`
