### ISSUE TITLE
BraintreeHttp-Dotnet.dll needs to be strongly named if used in .Net

### ISSUE THREAD

**Issue by ManlyBoy** [paypal/Checkout-NET-SDK#22]
BraintreeHttp-Dotnet.dll needs to be strongly named for it to work in .Net Framework 4.7.2 instances. **So will the V2 PayPalSDK itself.**

This dll is a dependency of the v2 PayPalSDK and until it is strongly signed, the V2 SDK will only work in the .NetCore world despite it supposedly being able to be used in .Net > 4.5 (See comments).

Braintree themselves have no idea who owns the BraintreeHttp-Dotnet.dll. I assume it is PayPal so who do you contact that deals with this SDK? Braintree have recommended I contact PayPal. Who would that be?

{"Message":"An error has occurred.","ExceptionMessage":"Could not load file or assembly 'BraintreeHttp-Dotnet, Version=0.1.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)","ExceptionType":"System.IO.FileLoadException","StackTrace":" at MCApi.Controllers.PayPalController.d__1.MoveNext()\r\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.Start[TStateMachine](TStateMachine& stateMachine)\r\n at MCApi.Controllers.PayPalController.GetOrderDetails(String orderId, Boolean debug)\r\n at lambda_method(Closure , Object , Object[] )\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_3.b__2(Object instance, Object[] methodParameters)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()\r\n at System.Web.Http.Controllers.ActionFilterResult.d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__15.MoveNext()"}

Is this dll available as a separate public repository?

**Comment by WSSC-Jonathan** [comment]
This looks unrelated to this repo. It looks like this DLL is 2 years old and part of Braintree. The braintreepayments NuGet package page (https://www.nuget.org/profiles/braintreepayments) shows two packages, the one you mention and the main Braintree package.

**Comment by tiffanyrzhou** [comment]
@ManlyBoy  This sdk no longer uses the briantreehttp package.
