### ISSUE TITLE
PATCH Shipping Address returns INVALID_JSON_POINTER_FORMAT

### ISSUE THREAD

**Issue by ApsBhasin** [paypal/Checkout-NET-SDK#31]
**General information**
Environment: sandbox
PayPal Debug ID : 4a559b99b6fa1
.NET Framework 4.6.1, PayPalCheckoutSdk 1.0.2, BraintreeHttp-Dotnet 0.3.0

**Issue**
I am trying to patch Shipping address and name for an Order with Intent: Capture and Status Approved. The response for Patch Request is throwing an Issue: "INVALID_JSON_POINTER_FORMAT".

My Patch Request is built as below:
```
[
   {
      "op":"replace",
      "path":"/purchase_units/@reference_id=='default'/shipping",
      "value":{
         "address":{
            "address_line_1":"Adrress Company",
            "address_line_2":"1 Street",
            "admin_area_1":"City",
            "admin_area_2":"area",
            "country_code":"GB",
            "postal_code":"KT2 5LQ"
         },
         "name":{
            "full_name":"Test Name"
         }
      }
   }
]
```

HTTP Response:
```
{  
   "name":"UNPROCESSABLE_ENTITY",
   "details":[  
      {  
         "field":"path",
         "value":"/purchase_units/0/shipping",
         "location":"body",
         "issue":"INVALID_JSON_POINTER_FORMAT",
         "description":"Path should be a valid JSON Pointer https://tools.ietf.org/html/rfc6901 that references a location within the request where the operation is performed."
      }
   ],
   "message":"The requested action could not be performed, semantically incorrect, or failed business validation.",
   "debug_id":"4a559b99b6fa1",
   "links":[  
      {  
         "href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_JSON_POINTER_FORMAT",
         "rel":"information_link",
         "method":"GET"
      }
   ]
}
```

After running a few tests I realised when I add a random reference_id to the path then the error displays the correct path and issue displays "REFERENCE_ID_NOT_FOUND", which is the correct expected behaviour. But as soon as the correct reference_id is sent, it is always replaced by 0 as array index and PayPal does not support JSON pointers in arrays.

Example of test with non-existent reference_id == 'random'
```
{
   "name":"UNPROCESSABLE_ENTITY",
   "details":[
      {
         "field":"path",
         "value":"/purchase_units/@reference_id=='random'/shipping",
         "location":"body",
         "issue":"REFERENCE_ID_NOT_FOUND",
         "description":"Filter expression value is incorrect. Please check the value of the reference_id and try again."
      }
   ],
   "message":"The requested action could not be performed, semantically incorrect, or failed business validation.",
   "debug_id":"284271a8dd47d",
   "links":[
      {
         "href":"https://developer.paypal.com/docs/api/orders/v2/#error-REFERENCE_ID_NOT_FOUND",
         "rel":"information_link",
         "method":"GET"
      }
   ]
}
```

**Comment by ganeshramc** [comment]
Hi we had an internal issue with that. Can you please check again to see if you still get an index instead of reference id?

**Comment by ApsBhasin** [comment]
Hi Ganeshram, 
I am able to see reference id being sent correctly instead of index now, which is progress. But now I see a different error which doesn't give any real explanation.

**See below the Patch Request that is generated and sent**
```
[
   {
      "op":"replace",
      "path":"/purchase_units/@reference_id=='default'/shipping",
      "value":{
         "address":{
            "address_line_1":"test order",
            "address_line_2":"do not ship",
            "admin_area_1":"Kingston upon Thames",
            "country_code":"GB",
            "postal_code":"KT2 6XX"
         },
         "name":{
            "full_name":"Ajitpal Bhasin"
         }
      }
   }
]
```
**on client execute I see the below error**:

```
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","debug_id":"829b8b7ee8787","details":[],"links":[]}

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: BraintreeHttp.HttpException: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","debug_id":"3f7fd24a3eb2","details":[],"links":[]}
```
Can you please try to patch shipping for an order with status "approved" on your end? Hopefully you will see the same result and it might be easier to track down the main issue then.

**Comment by ganeshramc** [comment]
Hey so seems like you are patching the whole shipping object but we only support shipping the separate resources inside shipping. Take a look here: https://developer.paypal.com/docs/api/orders/v2/#orders_patch

So if you want patch address, your path should be /purchase_units/@reference_id=='default'/shipping/address and the value should be the value that you would pass as value for address in the shipping object.

**Comment by ApsBhasin** [comment]
Yes that makes more sense now. It works perfectly fine now if I send a patch request just for address. Thank you for picking up on this.
