### ISSUE TITLE
Invalid Usage of HttpClient

### ISSUE THREAD

**Issue by DanielStout5** [paypal/Checkout-NET-SDK#33]
The way this library works, every request will create and dispose of two HttpClients (One to retrieve an access token, one for the actual request).

This is not the correct way to use HttpClient, and it causes socket exhaustion in high-load scenarios. See this blog post recommended by Microsoft for details: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

You should use the same HttpClient for both requests, and the library consumer should be able to provide pass that HttpClient (retrieved from IHttpClientFactory or similar) into the constructor for the PayPalHttpClient.

**Comment by Mike-E-wins** [comment]
Does anyone have any guidance on how to appropriately handle these HttpClients in .NET Core?

**Comment by Mike-E-wins** [comment]
FWIW I am doing the following:

```
public sealed class ProtocolClient : PayPalHttpClient
{
	readonly static FieldInfo Field = typeof(HttpClient)
	                                   .GetField("client", BindingFlags.Instance | BindingFlags.NonPublic) ?? throw new InvalidOperationException("Could not locate client field.");

	public ProtocolClient(System.Net.Http.HttpClient actual, PayPalEnvironment environment,
	                      string? refreshToken = null)
		: base(environment, refreshToken)
	{
		var current = (System.Net.Http.HttpClient)Field.GetValue(this);
		actual.BaseAddress = current.BaseAddress;
		foreach (var header in current.DefaultRequestHeaders)
		{
			actual.DefaultRequestHeaders.Add(header.Key, header.Value);
		}

		Field.SetValue(this, actual);
	}
}
```

Yuck? Yuck. 🤮

Also, the .NET documentation suffers from some broken code in its own right.  For instance, [this page](https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/#set-up-the-environment)'s `ObjectToJSONString` never flushes the `XmlDictionaryWriter`, so the output isn't guaranteed to be complete and therefore valid.  FWIW I am using the following for my serialization purposes and foregoing the dictionary writer altogether:

```
	public sealed class Serializer<T>
	{
		public static Serializer<T> Default { get; } = new Serializer<T>();

		Serializer() : this(new DataContractJsonSerializer(typeof(T),
		                                                   new DataContractJsonSerializerSettings
		                                                   {
			                                                   UseSimpleDictionaryFormat = true
		                                                   })) {}

		readonly XmlObjectSerializer _serializer;

		public Serializer(XmlObjectSerializer serializer) => _serializer = serializer;

		public string Get(T parameter)
		{
			using var stream = new MemoryStream();

			_serializer.WriteObject(stream, parameter);

			stream.Position = 0;

			using var reader = new StreamReader(stream);
			var       result = reader.ReadToEnd();
			return result;
		}
	}
```

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback.We will close this issue, and look into improving the way http clients are used. Thanks.
