### ISSUE TITLE
Client Won't Cache Access Tokens

### ISSUE THREAD

**Issue by DanielStout5** [paypal/Checkout-NET-SDK#34]
Your own documentation says "Rather than generate an OAuth 2.0 access token for each transaction, cache tokens. See OAuth 2.0 authorization protocol." but this code will request a new access token every time. 

Even if the PayPalHttpClient is configured as a singleton (bad idea - it doesn't seem to have been written in a thread safe way!), the retrieved access tokens from fetchAccessToken will have a `createdDate` of 0001-01-01, since the constructor isn't executed when the JSON is deserialized.

That means every token is immediately considered expired, so no tokens are ever re-used.

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback.We will close this issue, and look into improving the way http clients are used. Thanks.

**Comment by DanielStout5** [comment]
I don't think you should close issues like this unless you've actually pushed a fix for the issue. It gives a false and misleading impression that the bug has been resolved.
