### ISSUE TITLE
Are you getting this exception?

### ISSUE THREAD

**Issue by Juz05050505** [paypal/Checkout-NET-SDK#35]
Are you getting this exception?

`Method not found: 'System.Threading.Tasks.Task1<BraintreeHttp.HttpResponse> BraintreeHttp.HttpClient.Execute(BraintreeHttp.HttpRequest)'.`

If so, I'm having the same issue.

_Originally posted by @Enngage in https://github.com/paypal/Checkout-NET-SDK/issues/12#issuecomment-466328361_

**Comment by tiffanyrzhou** [comment]
Hello @Juz05050505. Thank you for reaching out.  Currently our best recommendation is to attempt the suggestion in the following comment. 
https://github.com/paypal/PayPal-NET-SDK/issues/360#issuecomment-433596015
