### ISSUE TITLE
Incorrect sample code

### ISSUE THREAD

**Issue by mnemanov** [paypal/Checkout-NET-SDK#39]
https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/

.Net sample code contains invalid code

```
OrderRequest orderRequest = new OrderRequest()
      {
        Intent = "CAPTURE", **//invalid, perhaps should be CheckoutPaymentIntent?**

        ApplicationContext = new ApplicationContext
        {

```

Edit: as I'm working thru the sample code I'm finding lots of other seemingly incorrect references.

**Comment by Mike-E-wins** [comment]
> Edit: as I'm working thru the sample code I'm finding lots of other seemingly incorrect references.

Does not give the impression of warm n' fuzzies, for sure.  I am attempting to decipher what the `INSTRUMENT_DECLINED` error is here:

https://developer.paypal.com/docs/checkout/integration-features/funding-failure/

But I do not see any field called `error` in any of the objects used in the SDK. 😞😭

**Comment by Mike-E-wins** [comment]
The other issue I've noticed is that I have attempted to use `actions.order.capture()` but if there is any method call prior to it, it seems to result in a failure as the window which contained the order is no longer available.

**Comment by tiffanyrzhou** [comment]
@mnemanov Thank you for reaching out and providing feedback. I have submitted a request to update https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/ and updated the readme.

**Comment by tiffanyrzhou** [comment]
@Mike-E-angelo . You're correct in that this sdk doesn't have error objects, we will look into adding this to the sdk in the future. 

The is the developer doc reference  to the error message. https://developer.paypal.com/docs/api/orders/v2/#error-INSTRUMENT_DECLINED.To mock such error please refer to this page: https://developer.paypal.com/docs/api-basics/sandbox/request-headers/#enable-negative-testing

**Comment by tiffanyrzhou** [comment]
> The other issue I've noticed is that I have attempted to use `actions.order.capture()` but if there is any method call prior to it, it seems to result in a failure as the window which contained the order is no longer available.

For this issue, please open a new issue and provide more context, so we can look into it further. Thanks!
