### ISSUE TITLE
ASP.NET Web Pages - Error trying to install PayPalCheckoutSdk 1.0.3 via NuGet

### ISSUE THREAD

**Issue by TonyBoySP** [paypal/Checkout-NET-SDK#41]
Hi.

I am trying to install PayPalCheckoutSdk 1.0.3 via NuGet to my ASP.NET Web Site project,, but I get this error:

**Could not install package 'PayPalCheckoutSdk 1.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

Reading the documentation on https://github.com/paypal/Checkout-NET-SDK, I thought that the min version of .NET framework was 4.6.1.

I am trying to follow the steps on the PayPal Checkout Basic Integration tutorial, but with this issue I am stuck at step 6 (Verify the transaction).

I am using Visual Studio Community 2015.

Any hint or idea what could be wrong? Thanks.

**Comment by tiffanyrzhou** [comment]
@TonyBoySP  Thanks for reaching out, I will try to reproduce the issue.

**Comment by tiffanyrzhou** [comment]
@TonyBoySP  Unfortunately , I wasn't able to reproduce your problem.  I was able to install the sdk via NuGet using a test application of .NETFramework Version of 4.6.1.  I right clicked my solution, and navigated the manage NuGet packages and use the visual studio UI to add the package. I am using 2019 mac  community visual studio. Researching your problem, seems like there are some issue surrounding 2015 version .
Please take a look at the footnote of https://docs.microsoft.com/en-us/dotnet/standard/net-standard
Some information that might be helpful
Checkout SDK : NET Standard 2.0
Samples in this Repo: .NETCore 2.0

To consolidate support across various support channels we have currently stopped opening new Github issues. Please visit https://www.paypal.com/support to submit your request or ask questions within our community forum
````
Attempting to gather dependency information for package 'PayPalCheckoutSdk.1.0.3' with respect to project 'test', targeting '.NETFramework,Version=v4.6.1'
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/paypalcheckoutsdk/index.json
Total number of results gathered : 6
Gathering dependency information took 4.24 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	1.1 ms
Attempting to resolve dependencies for package 'PayPalCheckoutSdk.1.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'PayPalCheckoutSdk.1.0.3'
Resolved actions to install package 'PayPalCheckoutSdk.1.0.3'
Retrieving package 'PayPalCheckoutSdk 1.0.3' from 'nuget.org'.
For adding package 'PayPalCheckoutSdk.1.0.3' to project 'test' that targets 'net461'.
For adding package 'PayPalCheckoutSdk.1.0.3' to project 'test' that targets 'net461'.
Adding package 'PayPalCheckoutSdk.1.0.3' to folder '/Users/../Projects/test/packages'
Added package 'PayPalCheckoutSdk.1.0.3' to folder '/Users/.../Projects/test/packages'
Added package 'PayPalCheckoutSdk.1.0.3' to folder '/Users/.../Projects/test/packages' from source 'https://api.nuget.org/v3/index.json'
Added reference 'PayPalCheckoutSdk' to project 'test'.
Added package 'PayPalCheckoutSdk.1.0.3' to 'packages.config'
Added file 'packages.config' to project 'test'.
Successfully installed 'PayPalCheckoutSdk 1.0.3' to test
Executing nuget actions took 76.49 ms

PayPalCheckoutSdk successfully added.`

```
