### ISSUE TITLE
How to validate payment_method_nonce with this SDK

### ISSUE THREAD

**Issue by balkarov** [paypal/Checkout-NET-SDK#42]
Hello.
I use PayPal smart button in HTML/JS (client side) and use Execute orderId with .net sdk.

But now I want to implement paypal in iOS platform.
I found docs only with braintreepayments. But in this way client side send `payment_method_nonce`
How validate this order?

**Comment by tiffanyrzhou** [comment]
@balkarov  Thanks for reaching out. We will be launching PayPal SDK for iOS soon. It will be available later in the year.
