### ISSUE TITLE
Request get stuck and not giving any response!

### ISSUE THREAD

**Issue by MuhammadAfnanZafar** [paypal/Checkout-NET-SDK#43]
Hi. i have tried your code but here in my case request stuck every time i couldn't get any response! The request is stuck somewhere and not giving any sort of response nor any error

`
public async static Task<string> test()
        {
            OrderRequest orderRequest = new OrderRequest()
            {

                CheckoutPaymentIntent = "CAPTURE",
                
                ApplicationContext = new ApplicationContext
                {
                    ReturnUrl = "http://localhost:44382/cont/act",
                    CancelUrl = "http://localhost:44382/cont/act"
                },
                PurchaseUnits = new List<PurchaseUnitRequest>
                 {
                 new PurchaseUnitRequest {

        AmountWithBreakdown = new AmountWithBreakdown
        {
          CurrencyCode = "USD",
          Value = "220.00"
        },
        Payee = new Payee
        {
          Email = "example@personal.example.com"
        }
      }
    }
            };
            var request = new OrdersCreateRequest();
          //  request.Prefer("return=representation");
            request.RequestBody(orderRequest);
           ///// Here i am not returning back and the request gets stuck
           HttpResponse response = await client().Execute(request);
            var statusCode = response.StatusCode;
            Order result = response.Result<Order>();
            return "string";
        }

        public static PayPalHttpClient client()
        {
            string clientId = "id";
            string clientSecret = "secret";

            // Creating a sandbox environment
            PayPalEnvironment environment = new SandboxEnvironment(clientId, clientSecret);

            // Creating a client for the environment
            PayPalHttpClient client = new PayPalHttpClient(environment);
            return client;
        }`

**Comment by tiffanyrzhou** [comment]
Hi @MuhammadAfnanZafar. Can you try the proposed solution here https://github.com/paypal/Checkout-NET-SDK/issues/48
