### ISSUE TITLE
Error during CreateOrder request

### ISSUE THREAD

**Issue by LuigiElleBalotta** [paypal/Checkout-NET-SDK#44]
Hello, i'm getting an error while executing a request with the PaypalHttpClient.
I'm going to give you the stacktrace that i'm getting with dotnet:
https://pastebin.com/MvJ0dE9S

This is the gist to the code i'm using: 
https://gist.github.com/LuigiElleBalotta/4f6f3565a06fe87765420300da0c1118

The error is thrown after line 100.

Thanks for the help!

**Comment by danjrichardson** [comment]
You may need to set the request to use Tls12.
```
  var protocol = ServicePointManager.SecurityProtocol;
  ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

  try
  {
      // send request to PayPal
      var response = await PayPalClient.client().Execute(request);
      var result = response.Result<Order>();

      // return order
      return result;
  }
  catch { throw; }
  finally
  {
      ServicePointManager.SecurityProtocol = protocol;
  }
```

**Comment by tiffanyrzhou** [comment]
Hi @LuigiElleBalotta. As @danjrichardson suggested you would need to use tls12 or higher according to paypal security guidelines https://developer.paypal.com/docs/api/info-security-guidelines/#security-best-practices-for-paypal-integrations.
Additional Information, you might want to consider: 
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls
