### ISSUE TITLE
Handling `INSTRUMENT_DECLINED`

### ISSUE THREAD

**Issue by Mike-E-wins** [paypal/Checkout-NET-SDK#45]
On this page:
https://developer.paypal.com/docs/checkout/integration-features/funding-failure/

There's mention of a `details.error`, but I am not seeing this on the `Order` object.  I am assuming that when the call returns from the API the `Order` object is being used.  Or are we cast the `HttpResponse` to another object in case there's an error?  Or will casting to an `Order` cause an error in this case?

Knowing how to handle these conditions in .NET would be greatly valuable and appreciated.  Thank you for any assistance/knowledge you can provide. 👍

**Comment by Mike-E-wins** [comment]
@ganeshramc @rajarampadmanathan @tiffanyrzhou @rsdighe76 is this a supported product?  Seems suspiciously quiet/inactive for a component of a major ecommerce platform solution.  Any guidance/context/pointers would be greatly appreciated!

**Comment by rajarampadmanathan** [comment]
HI..
Above referenced document is for Client side JS SDK.

For server side .NET SDK, 
in case of successful order capture API call, [Order resource](https://developer.paypal.com/docs/api/orders/v2/#orders-capture-response) will be returned in HTTP response. HTTP status code will be 201/200(idempotent response)

In case of any failure 4XX/5XX [Error response](https://developer.paypal.com/docs/api/orders/v2/#definition-error) will be returned. Currently there is no class in SDK for this error object. you can create custom class for handling this error object.

**Comment by Mike-E-wins** [comment]
Great thank you for taking the time to validate my understanding here @rajarampadmanathan.  My concern as well is the other numerous issues posted to this board that have also gone unanswered.  Strange seeing this from a multi-billion dollar organization whose primary initiative is money derived from commerce.
