### ISSUE TITLE
Where is the source code of PayPalHttp-Dotnet?

### ISSUE THREAD

**Issue by sonny-chen** [paypal/Checkout-NET-SDK#47]
We need to be able to make the SDK use a custom HTTP proxy and be able to set/change it on the fly. To do this we need to patch PayPalHttp-Dotnet, but we can't find its source code.

There are a number of PayPalHttp-* repos [available here](https://github.com/paypal?q=paypalhttp&type=&language=) for numerous frameworks except for .NET. Would you please upload the source for .NET? 

EDIT: Interestingly, the Braintree SDK has the same "issue." There are [various BraintreeHttp-* repos](https://github.com/braintree?q=braintreehttp&type=&language=) for a number of languages, but the BraintreeHttp-Dotnet is no where to be seen.

**Comment by tiffanyrzhou** [comment]
@sonny-chen https://github.com/paypal/paypalhttp_dotnet
