### ISSUE TITLE
Method never returns - PayPalHttp.HttpClient.Execute(OrdersCreateRequest)

### ISSUE THREAD

**Issue by sonny-chen** [paypal/Checkout-NET-SDK#48]
The [method never returns issue](https://github.com/paypal/PayPal-NET-SDK/issues/360) that is in PayPal-NET-SDK, is still present in Checkout-NET-SDK.

The [proposed workaround](https://github.com/paypal/PayPal-NET-SDK/issues/360#issuecomment-433596015) helps but doesn't always work. The method still doesn't return on occasions, especially on application start/first execution.

As PayPal has been aware of this issue for over a year now, is there a fix coming?

**Comment by sonny-chen** [comment]
Thanks to the recently posted [source code](https://github.com/paypal/paypalhttp_dotnet) of PayPalHttp-Dotnet, it becomes clear that the problem we're observing occurs when accessToken is null or expired. 

When one of the injectors tries to get the bearer token, the HttpClient.Execute() method never returns causing a time out exception. However since the token is cached during this, subsequent calls to the method succeeds until the token expires or the application restarts.

These injectors uses async/await internally but aren't called with async/await by PayPalHttp-Dotnet. This somehow causes breakage in certain scenarios, such as when used in ASP.NET.

Dropping the async wrapping around AccessTokenClient.Execute() in [PayPalHttpClient.cs](https://github.com/paypal/Checkout-NET-SDK/blob/develop/PayPalCheckoutSdk/Core/PaypalHttpClient.cs) solved the problem for us.

Interestingly, there is a comment immediately above the offending code that reads "make fetch access token call sync to avoid deadlock." It appears that this problem was look into before, but unfortunately the previous fix wasn't enough.

**Comment by MKI-Miro** [comment]
Hi, I am facing this issue now, Can you please explain more clearly what do i need to do to get it work?

**Comment by sonny-chen** [comment]
We could be seeing different root causes -- I just doubled checked and can confirm that dropping the async wrapping still fixes the problem for us.

Assuming the problem you're facing is also caused by the SDK retrieving an access token, try getting your own access token and then modify PayPalHttpClient.cs to have it use your token instead, thus completely bypassing the AuthorizationInjector. This said, our application still works even if we let the SDK get its own access token (leaving accessToken null).

Our applications need to do something we can't do through the SDK, so we have our own access token anyway.

```
-            authorizationInjector = new AuthorizationInjector(this, environment, refreshToken);
+            authorizationInjector = new AuthorizationInjector(this, environment, accessToken, refreshToken);

-            public AuthorizationInjector(HttpClient client, PayPalEnvironment environment, string refreshToken)
+            public AuthorizationInjector(HttpClient client, PayPalEnvironment environment, string accessToken, string refreshToken)
            {
                this.environment = environment;
                this.client = client;
                this.refreshToken = refreshToken;
+                if (!string.IsNullOrWhiteSpace(accessToken))
+                    this.accessToken = new AccessToken() {
+                        Token = accessToken,
+                        TokenType = "Bearer",
+                        ExpiresIn = 3600
+                };
            }
```
