### ISSUE TITLE
Is this the correct library to use to manage subscriptions

### ISSUE THREAD

**Issue by runxc1** [paypal/Checkout-NET-SDK#50]
I am looking over the Paypal Rest Subscription documentation and trying to see if this is the PayPal library to be used as there are a number of abandoned Paypal .net libraries.
https://developer.paypal.com/docs/subscriptions/integrate/#1-set-up-your-development-environment

**Comment by tiffanyrzhou** [comment]
Hi @runxc1. The Checkout SDK currently only supports Orders v2 and Payments v2. We do not have plans to incorporate PayPal Subscription API as part of this SDK bundle. We have referred this request to the team that manages the Subscription API and they will look to add it as part of their roadmap.
