### ISSUE TITLE
issue making strongly named assembly

### ISSUE THREAD

**Issue by zaferaydinosf** [paypal/Checkout-NET-SDK#51]
Hello,
`PayPalCheckoutSdk.dll` is not signed and not a strongly named assembly. As I am referencing it in a signed library, I need to have a signed version of `PayPalCheckoutSdk` as well. 
For this reason, I have signed the `PayPalCheckoutSdk.dll` using `ilasm` tool and generated a strong name assembly. There is no issue until here. However, `PayPalCheckoutSdk` has a pre-requisites - `PayPalHttp` - which is also not signed. I had to sign it too and did. But I am getting the following build errors when I have both signed:

`The type 'HttpClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`
and
`'PayPalHttpClient' does not contain a definition for 'Execute' and no accessible extension method 'Execute' accepting a first argument of type 'PayPalHttpClient' could be found (are you missing a using directive or an assembly reference?)`

As `PayPalHttp` is signed now, `PayPalCheckoutSdk` should look for the signed one somehow. But it seems still trying to find unsigned one with `PublicKeyToken=null`. How can we work with both dlls signed?

**Comment by tiffanyrzhou** [comment]
Hi @zaferaydinosf. Can you provide what .NET Framework or .NET Core you are using?

**Comment by tiffanyrzhou** [comment]
@zaferaydinosf The signed version of PayPalCheckoutSdk and PayPalHttpClient should be available via NuGet.
https://www.nuget.org/packages/PayPalCheckoutSdk/
https://www.nuget.org/packages/PayPalHttp/

To consolidate support across various support channels we have currently stopped opening new Github issues. Please visit https://www.paypal.com/support to submit your request or ask questions within our community forum
