### ISSUE TITLE
How to configure proxy?

### ISSUE THREAD

**Issue by talalong** [paypal/Checkout-NET-SDK#52]
The SDK was tested on my local maschine and it worked just fine. But It didn't on the shared hosting server, because I had to use proxy server. Is there any option for me to set proxy for every request (like using `WebProxy`)?
Here is a sample of mine calling a order using transactionID. This code below works only on my local PC. But not on remote server. I need to set a proxy address somewhere but `web.config`

```
var request = new OrdersGetRequest(order.TransactionId);
var response = await PayPalClient.client().Execute(request);
var result = response.Result<PayPalCheckoutSdk.Orders.Order>();
```

**Comment by talalong** [comment]
@WSSC-Jonathan Thank you sur, I came up with the same idea as yours. But your implementation is clearly much better.
I will check it later and then close this issue.

**Comment by talalong** [comment]
> We had to write our own HTTP client that adds the proxy client to the base class. Took a little fiddling to get the code correct, but this is what we ended up with. The ability to add a proxy directly to the PayPalHttp.ProxyClient would be a great advantage.
> 
> ```
> using System.Net;
> using System.Net.Http;
> using System.Net.Http.Headers;
> using System.Reflection;
> using System.Threading.Tasks;
> using PayPalCheckoutSdk.Core;
> 
> namespace PayPalExtensions
> {
>     public class ProxiedPayPalHttpClient : PayPalHttp.HttpClient
>     {
>         private WebProxy _proxy;
>         private PayPalEnvironment _environment;
> 
>         private PayPalHttp.IInjector _gzipInjector;
>         private PayPalHttp.IInjector _authInjector;
> 
>         public ProxiedPayPalHttpClient(PayPalEnvironment environment, WebProxy proxy)
>             : base(environment)
>         {
>             _environment = environment;
>             _proxy = proxy;
> 
>             OverrideClient();
>             SetupInjectors();
>         }
> 
>         public ProxiedPayPalHttpClient(PayPalEnvironment environment, string url, string username = "", string password = "")
>             : base(environment)
>         {
>             _environment = environment;
>             _proxy = SetupProxy(url, username, password);
> 
>             OverrideClient();
>             SetupInjectors();
>         }
> 
>         public WebProxy SetupProxy(string url, string username, string password)
>         {
>             var proxy = new WebProxy(url)
>             {
>                 BypassProxyOnLocal = true,
>                 UseDefaultCredentials = true
>             };
> 
>             if (!string.IsNullOrEmpty(username) || !string.IsNullOrEmpty(password))
>                 proxy.Credentials = new NetworkCredential(username, password);
> 
>             return proxy;
>         }
> 
>         private void OverrideClient()
>         {
>             var handler = new HttpClientHandler
>             {
>                 Proxy = _proxy
>             };
> 
>             var client = new HttpClient(handler, true) { BaseAddress = new Uri(environment.BaseUrl()) };
>             client.DefaultRequestHeaders.Add("User-Agent", GetUserAgent());
> 
>             SetClient(client);
>         }
> 
>         private void SetupInjectors()
>         {
>             _gzipInjector = new GzipInjector();
>             _authInjector = new AuthorizationInjector(_proxy, _environment);
> 
>             AddInjector(_gzipInjector);
>             AddInjector(_authInjector);
>         }
> 
>         protected void SetClient(HttpClient client)
>         {
>             var type = GetType();
> 
>             while (type != null)
>             {
>                 var field = type.GetField("client", BindingFlags.Instance | BindingFlags.NonPublic);
> 
>                 if (field != null)
>                 {
>                     field.SetField("client", client);
>                     break;
>                 }
> 
>                 type = type.BaseType;
>             }
>         }
> 
>         private class AuthorizationInjector : PayPalHttp.IInjector
>         {
>             private WebProxy _proxy;
>             private PayPalEnvironment _environment;
> 
>             private AccessToken _accessToken;
> 
>             public AuthorizationInjector(WebProxy proxy, PayPalEnvironment environment)
>             {
>                 _environment = environment;
>                 _proxy = proxy;
>             }
> 
>             public void Inject(PayPalHttp.HttpRequest request)
>             {
>                 if (!request.Headers.Contains("Authorization") && !(request is AccessTokenRequest || request is RefreshTokenRequest))
>                 {
>                     if (_accessToken == null || _accessToken.IsExpired())
>                         _accessToken = FetchAccessToken().Result<AccessToken>();
> 
>                     request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _accessToken.Token);
>                 }
>             }
> 
>             private PayPalHttp.HttpResponse FetchAccessToken()
>             {
>                 var client = new ProxiedPayPalHttpClient(_environment, _proxy);
>                 var request = new AccessTokenRequest(_environment, null);
> 
>                 return Task.Run(async () => await client.Execute(request)).Result;
>             }
>         }
> 
>         private class GzipInjector : PayPalHttp.IInjector
>         {
>             public void Inject(PayPalHttp.HttpRequest request)
>             {
>                 request.Headers.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
>             }
>         }
>     }
> }
> ```

@WSSC-Jonathan I think the overriding of PaypalHttpClient using SetClient() doesn't work, because `SetField()` doesn't exist. I was trying to replace it with `SetValue("client", client)`, but no success. Can you please help me out with that?

**Comment by WSSC-Jonathan** [comment]
Sorry it should be:

```
protected void SetClient(HttpClient client)
{
    var type = GetType();

    while (type != null)
    {
        var field = type.GetField("client", BindingFlags.Instance | BindingFlags.NonPublic);

        if (field != null)
        {
            field.SetValue("client", client); // problem when you copy and paste and combine functions
            break;
        }

        type = type.BaseType;
    }
}

**Comment by talalong** [comment]
@WSSC-Jonathan Thank you so much Sir! I can now close this issue.
