### ISSUE TITLE
Incorrect structure of Order

### ISSUE THREAD

**Issue by syunakh** [paypal/Checkout-NET-SDK#8]
Now phone for payer has next format 
```
"phone": {
                "national_number": "",
                "country_code": "",
                "extension_number": ""
        }
```

but API responses the field as :
```
"phone": {
            "phone_number": {
                "national_number": "",
                "country_code": "",
                "extension_number": ""
            }
        }
```

**Comment by rajarampadmanathan** [comment]
Thanks for reporting the issue. Will look into it and get back to you.

**Comment by AndreasJilvero** [comment]
Having the same issue. Trying to provide phone info in `OrderRequest`, but PayPal complains about `phone_number` is missing in the request. However, there is no way for me to provide `phone_number` in the current `Phone` object.

**Comment by ganeshramc** [comment]
Hey, we had updated our APIs recently and we are working on updating the SDK as well. It should be released soon. Thank you for your patience.
